version: 2
jobs:
  build:
    docker:
      - image: eddyashton/eevm-ci-build:0.0.1
    steps:
      - checkout
      - run:
          name: Make build directory
          command: mkdir build
      - run:
          name: CMake
          command: cmake ..
          working_directory: build
      - run:
          name: Build
          command: make
          working_directory: build
      - run:
          name: Run tests
          command: make test
          working_directory: build
